const RESPONSE_CODE = {
  DEFAULT: "SUCCESS",
  LOGIN: "LOGIN",
  OTP: "OTP_VERIFIED",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  ERROR: "ERROR",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  NOT_VERIFIED: "NOT_VERIFIED",
  DUPLICATE: "DUPLICATE",
  FAILURE: "FAILURE",
  REDIRECT: "REDIRECT"
};

module.exports = {
  RESPONSE_CODE,
};
